### ISSUE TITLE
using IWshRuntimeLibrary;

### ISSUE THREAD

**Issue by Micke3rd** [evan-sctg/NirnAuctionHouse-ServerLink#1]
Hi Elo,
the solution out of the box dont know "using IWshRuntimeLibrary;"
Did you thought about to add the WSH dll to the source ?

**Comment by evan-sctg** [comment]
You need to go to  Project->Add Reference
In the section labeled "COM" select  "Windows Script Host Object Model" and click "OK"

**Comment by Micke3rd** [comment]
it's not about how usually add a reference, cause u already added the ref from the GAC.
my example shows u, that on all PC without WSH u would get a exception (missing WSH), because of that my hint how to avoid it with other deployment.

**Comment by evan-sctg** [comment]
WSH is Removed in Next Version as it was only used to create a shortcut which is no longer used. 
Thanks for your feedback

**Comment by Micke3rd** [comment]
u are welcome, i like the idea of the mod :-)
