### ISSUE TITLE
A few possible issues/requests

### ISSUE THREAD

**Issue by remedy1** [evan-sctg/NirnAuctionHouse-ServerLink#2]
Remembering prices would be nice. Not urgent but a nice to have. If it could pull from TTC a default price that would be nice as well.

It would be nice to know if an item in your inventory is already listed when you mouse over it, or else the 'auction item' right click should not be there, or else perhaps should be changed to 'cancel auction'.

It appears that multiple identical items cannot be listed. Perhaps due to lacking synthetic keys for items. If so this probably can't be fixed easily and I wouldn't consider it a high priority.

The first sync after listing almost never results in being able to see just listed items. The third sync after listing is usually when they show up. If I was certain this was just a delay issue I could avoid subsequent syncs. But users do like to see evidence that their activities were recognized. Even a 'just submitted auctions may not be immediately visible in listings' notification might help.

Also I had a scare when my mailbox was full. As this becomes more used this will likely become a problem. What happens in this circumstance? Can an order fail from this and would this count towards an account ban? It would be bad if a buyer got dinged because he couldn't send payment because sellers mailbox was full. (I don't know if this is possible with CoD)

Speaking of bans, you might want to consider failed order per total orders instead of a hard number. I intend to never have a failed sale but things can happen. Also visible failure rates on sellers would help.

On the whole this is AMAZING work and incredibly unbuggy considering how little user testing it has had, if any.

**Comment by evan-sctg** [comment]
Thanks for your feedback and kind words!
You gave me some good things to consider and test, which I'll start looking into.

As to price history, this is planned for a future release until then I have integrated into master merchant for pricing details. I am very excited about having our own pricing data very soon though :)

**Comment by remedy1** [comment]
Last night when syncing after marking a couple dozen items the server link crashed with the below error message. I looked for the referenced files but they weren't there. Maybe I waited too long. I know this isn't very helpful, but so you know there may be a problem syncing a lot of new listings.

Files that help describe the problem:
  C:\Users\Lisa\AppData\Local\Temp\WER4902.tmp.WERInternalMetadata.xml
  C:\Users\Lisa\AppData\Local\Temp\WER54B6.tmp.appcompat.txt
  C:\Users\Lisa\AppData\Local\Temp\WER54C7.tmp.mdmp

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by evan-sctg** [comment]
I do know there is a limit on how many items you can post, however at this time I am unsure as to what that number is or if it's actually related to this crash but I will start attempting to replicate this issue and thank you for bringing it to my attention

if you get this error again can you send me your saved variables file  (NirnAuctionHouse.lua in saved variables directory)

**Comment by evan-sctg** [comment]
Strange I've been testing and I've successfully posted 50 items in a single sync.( haven't tested more than 50 yet )
I'd really like to look at your saved variables file if you have this happen again
